# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2020 PHYTEC America, LLC - https://www.phytec.com
#

DTC_FLAGS := -@
DTC_FLAGS := -i arch/arm64/boot/dts/freescale

dtb-$(CONFIG_ARCH_MXC) += phytec-imx8qxp-phycore-rdk-emmc.dtb \
	phytec-imx8qxp-uart2.dtbo \
	phytec-imx8qxp-parallel-camera.dtbo \
	phytec-imx8qxp-lcd-018.dtbo \
	phytec-imx8qxp-bt.dtbo \
	phytec-imx8qxp-wifi.dtbo  \
	phytec-imx8qxp-lvds0-peb-lvds-01.dtbo \
	phytec-imx8qxp-lvds1-peb-lvds-01.dtbo \
	eth1-tx_250_ps.dtbo \
	eth1-rx_250_ps.dtbo \
	eth1-tx_500_ps.dtbo \
	eth1-rx_500_ps.dtbo \
	eth1-tx_750_ps.dtbo \
	eth1-rx_750_ps.dtbo \
	eth1-tx_1_ns.dtbo \
	eth1-rx_1_ns.dtbo \
	eth1-tx_1_25_ns.dtbo \
	eth1-rx_1_25_ns.dtbo \
	eth1-tx_1_50_ns.dtbo \
	eth1-rx_1_50_ns.dtbo \
	eth1-tx_1_75_ns.dtbo \
	eth1-rx_1_75_ns.dtbo \
	eth1-tx_2_00_ns.dtbo \
	eth1-rx_2_00_ns.dtbo \
	eth1-tx_2_25_ns.dtbo \
	eth1-rx_2_25_ns.dtbo \
	eth1-tx_2_50_ns.dtbo \
	eth1-rx_2_50_ns.dtbo \
	eth1-tx_2_75_ns.dtbo \
	eth1-rx_2_75_ns.dtbo \
	eth1-tx_3_00_ns.dtbo \
	eth1-rx_3_00_ns.dtbo \
	eth1-tx_3_25_ns.dtbo \
	eth1-rx_3_25_ns.dtbo \
	eth1-tx_3_50_ns.dtbo \
	eth1-rx_3_50_ns.dtbo \
	eth1-tx_3_75_ns.dtbo \
	eth1-rx_3_75_ns.dtbo \
	eth1-tx_4_00_ns.dtbo \
	eth1-rx_4_00_ns.dtbo




