# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2020 PHYTEC America, LLC - https://www.phytec.com
#

DTC_FLAGS := -@
DTC_FLAGS := -i arch/arm64/boot/dts/freescale

dtb-$(CONFIG_ARCH_MXC) += phytec-imx8qxp-phycore-rdk-emmc.dtb \
	phytec-imx8qxp-uart2.dtbo \
	phytec-imx8qxp-parallel-camera.dtbo \
	phytec-imx8qxp-lcd-018.dtbo \
	phytec-imx8qxp-bt.dtbo \
	phytec-imx8qxp-wifi.dtbo  \
	phytec-imx8qxp-lvds0-peb-lvds-01.dtbo \
	phytec-imx8qxp-lvds1-peb-lvds-01.dtbo
